version: '3.9'
services:
  web:
    container_name: web
    build: ./web
    volumes:
      - ./web:/var/www/app
    ports:
      - ${WEB_APP_PORT}:3000
    depends_on:
      - db
  db:
    container_name: db
    build: ./db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"